⚔️⚔️⚔️ GenAI Slayer ⚔️⚔️⚔️

[legal_case]
two_man_40_plus = "Tom & Jeryy"
tom_description = "Tom is you tell me who I am not arguing I am telling and is provable"
tom_win = "1/1 and 2/2 is existental for jerry"
question = "what would legal argumnet defnse for jerry"

[game]
status = "GAME ON"
⚔️⚔️⚔️⚔️⚔️⚔️⚔️⚔️⚔️⚔️⚔️⚔️⚔️⚔️⚔️

[abbreviations]
baf = "BS AS A FACT"
faf = "Fiction as a fACT"
fact = "FACT"
